# -*- coding: utf-8 -*-
"""Desafio 1 - Análise de Dados

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Tcv0RvbHNMmQTVKLoQYanz4bhGaKGtB2
"""

import sklearn

from sklearn import datasets

iris = datasets.load_iris()
iris

iris.data

iris.target

iris.feature_names

iris.target_names

"""## Resolução"""

import pandas as pd
import numpy as np

dados = iris.data
dados

dados = pd.DataFrame(dados)
dados

classes = iris.target
classes

classes = pd.DataFrame(classes)
classes

df_iris = pd.concat([dados,classes],axis=1)
df_iris

colnames = iris.feature_names
colnames

type(colnames)

colnames.append('classification')
colnames

df_iris.columns = colnames
df_iris

nomes =iris.target_names
nomes

df_iris['classification'] = df_iris['classification'].replace({0:'setosa', 1:'versicolor', 2:'virginica'})
df_iris

df_iris['classification'].value_counts()